### ISSUE TITLE
ERROR: subvolume is not read-only

### ISSUE THREAD

**Issue by MurzNN** [rkapl/btsdu#1]
Thanks for so useful tool, it really helps to understand how much real space "eats" each snapshot! But when I try to launch tool on not readonly snapshot, I got the error:
```
ERROR: subvolume /mnt/btrfs/my-subvolume is not read-only
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/btsdu-0.1.0/src/main.rs:164:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Can you please explain why this tool not works with readwrite snapshots, and is this possible to add this feature? Thanks!

**Comment by rkapl** [comment]
The tool works by running `btrfs send`, which gives it the differences between two snapshots. It then analyzes the size of the difference. However, `btrfs send` needs both snapshots to be readonly (see https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-send ).

As a work-around, I would suggest creating a readonly snapshot of the snapshot you want to analyze, analyze it and then delete it.
